create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  parent_name text not null,
  email text not null,
  phone text not null,
  child_name text not null,
  child_age int not null check (child_age between 8 and 16),
  interests text,
  notes text
);

alter table public.enrollments enable row level security;

create policy "service role can manage enrollments"
on public.enrollments
for all
to service_role
using (true)
with check (true);
